name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug: check token presence
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -z "$SONAR_TOKEN" ]; then
            echo "❌ SONAR_TOKEN is NOT set"
            exit 1
          else
            echo "✅ SONAR_TOKEN is set"
          fi

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=BAR
            -Dsonar.sources=.
            -Dsonar.login=$SONAR_TOKEN
